name: Say hello

on:
  push:
    branches:
      - main

jobs:
  hello_worl:
    runs-on: ubuntu-latest

    steps:
      - name: Say hello
        run: echo "Hello, world!"

      - name: Return Date
        run: date
      - run: ls -l
