name: Deployment Pipeline

on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v4
        with:
          node-version: '16.14.0'

      - uses: pnpm/action-setup@v4
        with:
          version: '8.14.1'

      - name: Install dependencies
        run: pnpm install

      - name: Lint
        run: pnpm run lint
